// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemMonitorowaniaWydatkowDomowych.Data;

#nullable disable

namespace SystemMonitorowaniaWydatkowDomowych.Migrations
{
    [DbContext(typeof(KontekstBazyDanych))]
    [Migration("20260603091953_UtworzenieTabel")]
    partial class UtworzenieTabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemMonitorowaniaWydatkowDomowych.Models.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("SystemMonitorowaniaWydatkowDomowych.Models.MetodaPlatnosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("MetodyPlatnosci");
                });

            modelBuilder.Entity("SystemMonitorowaniaWydatkowDomowych.Models.Wydatek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Kwota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MetodaPlatnosciId")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.HasIndex("MetodaPlatnosciId");

                    b.ToTable("Wydatki");
                });

            modelBuilder.Entity("SystemMonitorowaniaWydatkowDomowych.Models.Wydatek", b =>
                {
                    b.HasOne("SystemMonitorowaniaWydatkowDomowych.Models.Kategoria", "Kategoria")
                        .WithMany("Wydatki")
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SystemMonitorowaniaWydatkowDomowych.Models.MetodaPlatnosci", "MetodaPlatnosci")
                        .WithMany("Wydatki")
                        .HasForeignKey("MetodaPlatnosciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategoria");

                    b.Navigation("MetodaPlatnosci");
                });

            modelBuilder.Entity("SystemMonitorowaniaWydatkowDomowych.Models.Kategoria", b =>
                {
                    b.Navigation("Wydatki");
                });

            modelBuilder.Entity("SystemMonitorowaniaWydatkowDomowych.Models.MetodaPlatnosci", b =>
                {
                    b.Navigation("Wydatki");
                });
#pragma warning restore 612, 618
        }
    }
}
